In [1]:
import os
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
os.getcwd()

'c:\\Users\\kavou\\Downloads'

In [3]:
#import PIT data for 2018-2022 ia a list of dataframes
xls = pd.ExcelFile('2007-2022-HIC-Counts-by-CoC (2).xlsx')

n = 2022-2018+1
HIC_df_list = [pd.DataFrame() for _ in range(n)]

for num,year in enumerate(range(2022,2018-1,-1)):
    HIC_df_list[num] = pd.read_excel(xls, str(year), skiprows=[0])
    HIC_df_list[num].insert(1, 'Year', year)

In [4]:
#concatenate all dataframes into one
HIC_df = pd.DataFrame()
for df in HIC_df_list:
    try:
        df = df[df['CoC'].notna()]
        HIC_df = pd.concat([HIC_df, df])
    except:
        df = df.rename(columns={'CoC Number': 'CoC'})#some years the area code column is named CoC and some others it's named CoC Number
        df = df[df['CoC'].notna()]
        HIC_df = pd.concat([HIC_df, df])

In [5]:
#Filter out total rows
HIC_df = HIC_df[HIC_df.CoC!='Total']
HIC_df[['State','Code']] = HIC_df['CoC'].str.split("-").to_list()
HIC_df

,CoC,Year,"Total Year-Round Beds (ES, TH, SH)","Total Non-DV Year-Round Beds (ES, TH, SH)","Total HMIS Year-Round Beds (ES, TH, SH)","HMIS Participation Rate for Year-Round Beds (ES, TH, SH)",Total Year-Round Beds (ES),Total Year-Round Beds (TH),Total Year-Round Beds (SH),"Total Units for Households with Children (ES, TH, SH)","Total Beds for Households with Children (ES, TH, SH)","Total Beds for Households without Children (ES, TH, SH)","Total Beds for Households with only Children (ES, TH, SH)","Dedicated Veteran Beds (ES, TH, SH)","Dedicated Youth Beds (ES, TH, SH)",Total Year-Round Beds (ES).1,Total Non-DV Year-Round Beds (ES),Total HMIS Year-Round Beds (ES),HMIS Participation Rate for Year-Round Beds (ES),Total Seasonal Beds (ES),Total Overflow Beds (ES),Total Units for Households with Children (ES),Total Beds for Households with Children (ES),Total Beds for Households without Children (ES),Total Beds for Households with only Children (ES),Dedicated Veteran Beds (ES),Dedicated Youth Beds (ES),Total Year-Round Beds (TH).1,Total Non-DV Year-Round Beds (TH),Total HMIS Year-Round Beds (TH),HMIS Participation Rate for Year-Round Beds (TH),Total Units for Households with Children (TH),Total Beds for Households with Children (TH),Total Beds for Households without Children (TH),Total Beds for Households with only Children (TH),Dedicated Veteran Beds (TH),Dedicated Youth Beds (TH),Total Year-Round Beds (SH).1,Total Non-DV Year-Round Beds (SH),Total HMIS Year-Round Beds (SH),HMIS Participation Rate for Year-Round Beds (SH),Total Units for Households with Children (SH),Total Beds for Households with Children (SH),Total Beds for Households without Children (SH),Total Beds for Households with only Children (SH),Dedicated Veteran Beds (SH),Dedicated Youth Beds (SH),Total Year-Round Beds (RRH),Total Non-DV Year-Round Beds (RRH),Total HMIS Year-Round Beds (RRH),HMIS Participation Rate for Year-Round Beds (RRH),Total Units for Households with Children (RRH),Total Beds for Households with Children (RRH),Total Beds for Households without Children (RRH),Total Beds for Households with only Children (RRH),Dedicated Veteran Beds (RRH),Dedicated Youth Beds (RRH),Total Year-Round Beds (PSH),Total Non-DV Year-Round Beds (PSH),Total HMIS Year-Round Beds (PSH),HMIS Participation Rate for Year-Round Beds (PSH),Total Units for Households with Children (PSH),Total Beds for Households with Children (PSH),Total Beds for Households without Children (PSH),Total Beds for Households with only Children (PSH),Dedicated Veteran Beds (PSH),Dedicated Youth Beds (PSH),Dedicated Chronically Homeless Beds (PSH),Total Year-Round Beds (OPH),Total Non-DV Year-Round Beds (OPH),Total HMIS Year-Round Beds (OPH),HMIS Participation Rate for Year-Round Beds (OPH),Total Units for Households with Children (OPH),Total Beds for Households with Children (OPH),Total Beds for Households without Children (OPH),Total Beds for Households with only Children (OPH),Dedicated Veteran Beds (OPH),Dedicated Youth Beds (OPH),State,Code
0,AK-500,2022,2019,1952,1872,0.9272,1814,205,0,79,286,1720,13,0,97,1814,1772,1700,0.9372,60,6,42,154,1652,8,0,48,205,180,172,0.839,37,132,68,5,0,49,0,0,0,NaN,0,0,0,0,0,0,237,224,224,0.9451,22,77,154,6,43,24,705,705,499,0.7078,59,193,512,0,206,13,505,182,182,85,0.467,13,59,123,0,0,0,AK,500
1,AK-501,2022,1069,595,567,0.5304,801,268,0,126,406,624,39,12,56,801,408,396,0.4944,78,9,80,277,485,39,0,48,268,187,171,0.6381,46,129,139,0,12,8,0,0,0,NaN,0,0,0,0,0,0,137,99,99,0.7226,15,60,77,0,40,5,385,385,184,0.4779,26,47,338,0,180,0,189,97,97,0,0.0,10,47,50,0,0,0,AK,501
2,AL-500,2022,670,640,552,0.8239,431,205,34,43,121,542,7,100,19,431,413,413,0.9582,0,0,27,79,345,7,90,7,205,193,105,0.5122,16,42,163,0,10,12,34,34,34,1.0,0,0,34,0,0,0,206,206,206,1.0,33,97,109,0,40,18,1326,1326,1326,1.0,76,239,1087,0,523,0,50,64,64,64,1.0,6,20,44,0,0,0,AL,500
3,AL-501,2022,467,391,391,0.8373,314,153,0,88,276,191,0,58,0,314,263,263,0.8376,0,8,59,180,134,0,0,0,153,128,128,0.8366,29,96,57,0,58,0,0,0,0,NaN,0,0,0,0,0,0,197,175,175,0.8883,53,171,26,0,4,0,251,251,251,1.0,5,21,230,0,60,0,94,9,9,9,1.0,0,0,9,0,9,0,AL,501
4,AL-502,2022,246,56,0,0.0000,118,128,0,77,109,121,16,4,16,118,40,0,0.0,30,0,32,47,71,0,4,0,128,16,0,0.0,45,62,50,16,0,16,0,0,0,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,AL,502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,WV-500,2018,107,71,58,0.5421,67,40,0,24,61,46,0,7,0,67,51,45,0.6716,16,22,10,28,39,0,0,0,40,20,13,0.325,14,33,7,0,7,0,0,0,0,.,0,0,0,0,0,0,18,18,18,1,2,5,13,0,7,0,18,18,18,1,0,0,18,0,0,0,16,0,0,0,.,0,0,0,0,0,0,WV,500
393,WV-501,2018,275,253,240,0.8727,197,64,14,40,141,134,0,13,0,197,175,162,0.8223,0,0,22,77,120,0,13,0,64,64,64,1,18,64,0,0,0,0,14,14,14,1,0,0,14,0,0,0,73,73,73,1,4,12,61,0,0,0,398,398,398,1,65,155,243,0,110,0,112,108,108,108,1,0,0,108,0,0,0,WV,501
394,WV-503,2018,310,293,172,0.5548,255,55,0,24,65,234,11,17,11,255,238,141,0.5529,0,19,24,65,184,6,0,6,55,55,31,0.5636,0,0,50,5,17,5,0,0,0,.,0,0,0,0,0,0,19,19,19,1,5,14,5,0,0,0,165,162,162,0.9818,5,10,155,0,62,0,98,0,0,0,.,0,0,0,0,0,0,WV,503
395,WV-508,2018,901,649,565,0.6271,773,128,0,111,358,543,0,77,0,773,521,449,0.5809,10,7,101,342,431,0,24,0,128,128,116,0.9063,10,16,112,0,53,0,0,0,0,.,0,0,0,0,0,0,277,277,277,1,41,131,146,0,124,0,680,680,323,0.475,104,281,399,0,378,7,415,46,46,46,1,15,41,5,0,0,0,WV,508
396,WY-500,2018,560,508,401,0.7161,345,215,0,102,257,277,26,19,36,345,293,207,0.6,20,0,71,139,194,12,0,12,215,215,194,0.9023,31,118,83,14,19,24,0,0,0,.,0,0,0,0,0,0,32,29,29,0.9063,2,4,28,0,29,0,230,230,73,0.3174,35,73,157,0,157,0,209,0,0,0,.,0,0,0,0,0,0,WY,500

In [6]:
cols_to_keep = ['State','Year', 'Dedicated Veteran Beds (ES)','Dedicated Veteran Beds (ES, TH, SH)','Dedicated Veteran Beds (SH)','Dedicated Veteran Beds (TH)','Dedicated Youth Beds (ES)','Dedicated Youth Beds (ES, TH, SH)','Dedicated Youth Beds (SH)',
                'Dedicated Youth Beds (TH)','Total Beds for Households with Children (ES)','Total Beds for Households with Children (ES, TH, SH)', 'Total Beds for Households with Children (SH)','Total Beds for Households with Children (TH)',
                'Total Beds for Households with only Children (ES)','Total Beds for Households with only Children (ES, TH, SH)','Total Beds for Households with only Children (SH)','Total Beds for Households with only Children (TH)',
                'Total Beds for Households without Children (ES)','Total Beds for Households without Children (ES, TH, SH)','Total Beds for Households without Children (SH)','Total Beds for Households without Children (TH)',
                'Total Non-DV Year-Round Beds (ES)','Total Non-DV Year-Round Beds (ES, TH, SH)','Total Non-DV Year-Round Beds (SH)','Total Non-DV Year-Round Beds (TH)','Total Overflow Beds (ES)','Total Seasonal Beds (ES)',
                'Total Units for Households with Children (ES)', 'Total Units for Households with Children (ES, TH, SH)', 'Total Units for Households with Children (SH)', 'Total Units for Households with Children (TH)', 'Total Year-Round Beds (ES)',
                'Total Year-Round Beds (ES).1', 'Total Year-Round Beds (ES, TH, SH)', 'Total Year-Round Beds (SH)', 'Total Year-Round Beds (TH)']

In [7]:
new_df = HIC_df[cols_to_keep] #We're only keeping the columns we want
new_df

,State,Year,Dedicated Veteran Beds (ES),"Dedicated Veteran Beds (ES, TH, SH)",Dedicated Veteran Beds (SH),Dedicated Veteran Beds (TH),Dedicated Youth Beds (ES),"Dedicated Youth Beds (ES, TH, SH)",Dedicated Youth Beds (SH),Dedicated Youth Beds (TH),Total Beds for Households with Children (ES),"Total Beds for Households with Children (ES, TH, SH)",Total Beds for Households with Children (SH),Total Beds for Households with Children (TH),Total Beds for Households with only Children (ES),"Total Beds for Households with only Children (ES, TH, SH)",Total Beds for Households with only Children (SH),Total Beds for Households with only Children (TH),Total Beds for Households without Children (ES),"Total Beds for Households without Children (ES, TH, SH)",Total Beds for Households without Children (SH),Total Beds for Households without Children (TH),Total Non-DV Year-Round Beds (ES),"Total Non-DV Year-Round Beds (ES, TH, SH)",Total Non-DV Year-Round Beds (SH),Total Non-DV Year-Round Beds (TH),Total Overflow Beds (ES),Total Seasonal Beds (ES),Total Units for Households with Children (ES),"Total Units for Households with Children (ES, TH, SH)",Total Units for Households with Children (SH),Total Units for Households with Children (TH),Total Year-Round Beds (ES),Total Year-Round Beds (ES).1,"Total Year-Round Beds (ES, TH, SH)",Total Year-Round Beds (SH),Total Year-Round Beds (TH)
0,AK,2022,0,0,0,0,48,97,0,49,154,286,0,132,8,13,0,5,1652,1720,0,68,1772,1952,0,180,6,60,42,79,0,37,1814,1814,2019,0,205
1,AK,2022,0,12,0,12,48,56,0,8,277,406,0,129,39,39,0,0,485,624,0,139,408,595,0,187,9,78,80,126,0,46,801,801,1069,0,268
2,AL,2022,90,100,0,10,7,19,0,12,79,121,0,42,7,7,0,0,345,542,34,163,413,640,34,193,0,0,27,43,0,16,431,431,670,34,205
3,AL,2022,0,58,0,58,0,0,0,0,180,276,0,96,0,0,0,0,134,191,0,57,263,391,0,128,8,0,59,88,0,29,314,314,467,0,153
4,AL,2022,4,4,0,0,0,16,0,16,47,109,0,62,0,16,0,16,71,121,0,50,40,56,0,16,0,30,32,77,0,45,118,118,246,0,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,WV,2018,0,7,0,7,0,0,0,0,28,61,0,33,0,0,0,0,39,46,0,7,51,71,0,20,22,16,10,24,0,14,67,67,107,0,40
393,WV,2018,13,13,0,0,0,0,0,0,77,141,0,64,0,0,0,0,120,134,14,0,175,253,14,64,0,0,22,40,0,18,197,197,275,14,64
394,WV,2018,0,17,0,17,6,11,0,5,65,65,0,0,6,11,0,5,184,234,0,50,238,293,0,55,19,0,24,24,0,0,255,255,310,0,55
395,WV,2018,24,77,0,53,0,0,0,0,342,358,0,16,0,0,0,0,431,543,0,112,521,649,0,128,7,10,101,111,0,10,773,773,901,0,128
396,WY,2018,0,19,0,19,12,36,0,24,139,257,0,118,12,26,0,14,194,277,0,83,293,508,0,215,0,20,71,102,0,31,345,345,560,0,215

In [8]:
new_df = new_df.groupby(['State','Year']).sum().reset_index() #Add all state area codes
melt_df = new_df.melt(id_vars=['State','Year'], var_name='Column', value_name='Values') #melt the dataframe before pivoting
melt_df

     State  Year                       Column  Values
0       AK  2018  Dedicated Veteran Beds (ES)       0
1       AK  2019  Dedicated Veteran Beds (ES)       0
2       AK  2020  Dedicated Veteran Beds (ES)       0
3       AK  2021  Dedicated Veteran Beds (ES)       0
4       AK  2022  Dedicated Veteran Beds (ES)       0
...    ...   ...                          ...     ...
9620    WY  2018   Total Year-Round Beds (TH)     215
9621    WY  2019   Total Year-Round Beds (TH)     236
9622    WY  2020   Total Year-Round Beds (TH)     271
9623    WY  2021   Total Year-Round Beds (TH)     205
9624    WY  2022   Total Year-Round Beds (TH)     146

[9625 rows x 4 columns]

In [9]:
final_df = melt_df.pivot(index=['State','Column'], columns='Year')['Values'].reset_index()#now our dataframe is in a time series format
final_df

Year State                               Column  2018  2019  2020  2021  2022
0       AK          Dedicated Veteran Beds (ES)     0     0     0     0     0
1       AK  Dedicated Veteran Beds (ES, TH, SH)    14    15    14    12    12
2       AK          Dedicated Veteran Beds (SH)     0     0     0     0     0
3       AK          Dedicated Veteran Beds (TH)    14    15    14    12    12
4       AK            Dedicated Youth Beds (ES)    76    80    71    76    96
...    ...                                  ...   ...   ...   ...   ...   ...
1920    WY           Total Year-Round Beds (ES)   345   383   533   586   693
1921    WY         Total Year-Round Beds (ES).1   345   383   533   586   693
1922    WY   Total Year-Round Beds (ES, TH, SH)   560   619   804   791   839
1923    WY           Total Year-Round Beds (SH)     0     0     0     0     0
1924    WY           Total Year-Round Beds (TH)   215   236   271   205   146

[1925 rows x 7 columns]

In [10]:
#Create a column for Program Type
final_df[['Column_New','Program_Type']] = final_df.Column.str.split('(').tolist()
final_df.Column_New = final_df.Column_New.str.strip()
final_df[['Program_Type','to_drop']] = final_df.Program_Type.str.split(')').tolist()
final_df = final_df.drop(['Column','to_drop'], axis=1)
final_df

Year State  2018  2019  2020  2021  2022              Column_New Program_Type
0       AK     0     0     0     0     0  Dedicated Veteran Beds           ES
1       AK    14    15    14    12    12  Dedicated Veteran Beds   ES, TH, SH
2       AK     0     0     0     0     0  Dedicated Veteran Beds           SH
3       AK    14    15    14    12    12  Dedicated Veteran Beds           TH
4       AK    76    80    71    76    96    Dedicated Youth Beds           ES
...    ...   ...   ...   ...   ...   ...                     ...          ...
1920    WY   345   383   533   586   693   Total Year-Round Beds           ES
1921    WY   345   383   533   586   693   Total Year-Round Beds           ES
1922    WY   560   619   804   791   839   Total Year-Round Beds   ES, TH, SH
1923    WY     0     0     0     0     0   Total Year-Round Beds           SH
1924    WY   215   236   271   205   146   Total Year-Round Beds           TH

[1925 rows x 8 columns]

In [11]:
final_df.to_csv('HIC_GAvsUSA.csv', index=False)

In [12]:
changes_df = final_df[(final_df.Column_New=='Total Year-Round Beds')&(final_df.Program_Type=='ES, TH, SH')]
changes_df.insert(2, '2018 to 2019', (changes_df.loc[:,2019]-changes_df.loc[:,2018])/changes_df.loc[:,2018]*100)
changes_df.insert(4, '2019 to 2020', (changes_df.loc[:,2020]-changes_df.loc[:,2019])/changes_df.loc[:,2019]*100)
changes_df.insert(6, '2020 to 2021', (changes_df.loc[:,2021]-changes_df.loc[:,2020])/changes_df.loc[:,2020]*100)
changes_df.insert(8, '2021 to 2022', (changes_df.loc[:,2022]-changes_df.loc[:,2021])/changes_df.loc[:,2021]*100)
changes_df.sort_values(['2021 to 2022'], ascending=False)

Year,State,2018,2018 to 2019,2019,2019 to 2020,2020,2020 to 2021,2021,2021 to 2022,2022,Column_New,Program_Type
697,LA,2647,2.304496,2708,-4.726736,2580,-19.534884,2076,215.269750,6545,Total Year-Round Beds,"ES, TH, SH"
802,ME,2734,-17.556693,2254,4.170364,2348,14.011925,2677,73.963392,4657,Total Year-Round Beds,"ES, TH, SH"
312,DE,1122,-9.625668,1014,1.183432,1026,-8.284600,941,51.540914,1426,Total Year-Round Beds,"ES, TH, SH"
1397,OR,6419,11.341330,7147,-16.650343,5957,-10.777237,5315,37.478833,7307,Total Year-Round Beds,"ES, TH, SH"
32,AK,1940,-3.195876,1878,0.372737,1885,20.424403,2270,36.035242,3088,Total Year-Round Beds,"ES, TH, SH"
1362,OK,3339,-3.533992,3221,-3.725551,3101,-16.607546,2586,27.996906,3310,Total Year-Round Beds,"ES, TH, SH"
1747,VI,205,-61.951220,78,17.948718,92,-29.347826,65,27.692308,83,Total Year-Round Beds,"ES, TH, SH"
1817,WA,15016,-6.220032,14082,5.219429,14817,-3.394749,14314,19.309767,17078,Total Year-Round Beds,"ES, TH, SH"
522,ID,1413,3.750885,1466,7.571623,1577,-0.063412,1576,16.814721,1841,Total Year-Round Beds,"ES, TH, SH"
1012,MT,1376,-4.142442,1319,2.426080,1351,27.017024,1716,16.142191,1993,Total Year-Round Beds,"ES, TH, SH"
1257,NV,3033,0.989120,3063,2.938296,3153,17.411989,3702,14.613722,4243,Total Year-Round Beds,"ES, TH, SH"
67,AL,3188,-15.276035,2701,7.848945,2913,-17.816684,2394,13.366750,2714,Total Year-Round Beds,"ES, TH, SH"
172,CA,43548,6.333241,46306,15.028290,53265,13.736975,60582,13.246509,68607,Total Year-Round Beds,"ES, TH, SH"
1467,PR,955,-10.471204,855,-14.502924,731,-9.849521,659,13.201821,746,Total Year-Round Beds,"ES, TH, SH"
1082,ND,726,3.856749,754,0.397878,757,2.509908,776,12.757732,875,Total Year-Round Beds,"ES, TH, SH"
1782,VT,937,-8.964781,853,-3.516999,823,2.673147,845,12.071006,947,Total Year-Round Beds,"ES, TH, SH"
592,IN,5568,6.250000,5916,-1.605815,5821,-7.095001,5408,10.965237,6001,Total Year-Round Beds,"ES, TH, SH"
767,MD,5529,-4.087538,5303,-1.546295,5221,7.910362,5634,9.708910,6181,Total Year-Round Beds,"ES, TH, SH"
1677,UT,2968,-1.381402,2927,-2.118210,2865,-5.165794,2717,9.569378,2977,Total Year-Round Beds,"ES, TH, SH"
1537,SC,3001,2.332556,3071,-0.130251,3067,-9.194653,2785,8.150808,3012,Total Year-Round Beds,"ES, TH, SH"
1887,WV,1593,-5.021971,1513,-2.181097,1480,-2.027027,1450,7.793103,1563,Total Year-Round Beds,"ES, TH, SH"
907,MO,5773,1.610948,5866,1.909308,5978,-4.683841,5698,6.721657,6081,Total Year-Round Beds,"ES, TH, SH"
1152,NH,1349,-1.779096,1325,18.792453,1574,10.991105,1747,6.697195,1864,Total Year-Round Beds,"ES, TH, SH"
1117,NE,2390,7.029289,2558,8.053167,2764,-5.969609,2599,6.579454,2770,Total Year-Round Beds,"ES, TH, SH"
557,IL,10210,-2.654261,9939,2.958044,10233,-3.097821,9916,6.423961,10553,Total Year-Round Beds,"ES, TH, SH"
1187,NJ,7099,0.732498,7151,0.377570,7178,-17.107829,5950,6.403361,6331,Total Year-Round Beds,"ES, TH, SH"
1327,OH,9269,-0.409969,9231,0.238327,9253,-3.588026,8921,6.154019,9470,Total Year-Round Beds,"ES, TH, SH"
347,FL,19554,-4.791858,18617,-4.426062,17793,-2.596527,17331,6.127748,18393,Total Year-Round Beds,"ES, TH, SH"
1922,WY,560,10.535714,619,29.886914,804,-1.616915,791,6.068268,839,Total Year-Round Beds,"ES, TH, SH"
732,MA,17310,0.935875,17472,0.320513,17528,-3.531492,16909,5.908096,17908,Total Year-Round Beds,"ES, TH, SH"
277,DC,6721,-8.406487,6156,8.625731,6687,-6.206071,6272,5.197704,6598,Total Year-Round Beds,"ES, TH, SH"
1432,PA,12909,-1.719730,12687,0.803973,12789,-7.404801,11842,4.965377,12430,Total Year-Round Beds,"ES, TH, SH"
662,KY,2875,6.052174,3049,8.953755,3322,-3.973510,3190,4.702194,3340,Total Year-Round Beds,"ES, TH, SH"
1642,TX,18006,1.471732,18271,-0.711510,18141,0.986715,18320,4.394105,19125,Total Year-Round Beds,"ES, TH, SH"
837,MI,8531,1.160474,8630,3.870220,8964,-5.354752,8484,3.972183,8821,Total Year-Round Beds,"ES, TH, SH"
207,CO,7532,8.815720,8196,0.951684,8274,11.348803,9213,0.879192,9294,Total Year-Round Beds,"ES, TH, SH"
942,MP,30,0.000000,30,0.000000,30,0.000000,30,0.000000,30,Total Year-Round Beds,"ES, TH, SH"
1852,WI,4721,-4.384664,4514,-3.832521,4341,12.577747,4887,-0.450174,4865,Total Year-Round Beds,"ES, TH, SH"
1502,RI,1003,-5.084746,952,4.306723,993,-12.487412,869,-1.956272,852,Total Year-Round Beds,"ES, TH, SH"
1712,VA,5303,-3.978880,5092,-2.336999,4973,14.317313,5685,-2.233949,5558,Total Year-Round Beds,"ES, TH, SH"
872,MN,6660,-4.564565,6356,5.884204,6730,20.208024,8090,-2.608158,7879,Total Year-Round Beds,"ES, TH, SH"
1047,NC,7963,0.251162,7983,-0.688964,7928,-7.580727,7327,-2.988945,7108,Total Year-Round Beds,"ES, TH, SH"
1607,TN,5674,-4.599930,5413,-6.521338,5060,7.292490,5429,-3.131332,5259,Total Year-Round Beds,"ES, TH, SH"
137,AZ,6683,-1.720784,6568,-7.445189,6079,5.461425,6411,-3.883949,6162,Total Year-Round Beds,"ES, TH, SH"
1572,SD,1090,-1.467890,1074,13.128492,1215,5.596708,1283,-3.897116,1233,Total Year-Round Beds,"ES, TH, SH"
487,IA,3026,-16.787839,2518,1.906275,2566,-0.350740,2557,-4.028158,2454,Total Year-Round Beds,"ES, TH, SH"
382,GA,7363,3.218797,7600,-2.460526,7413,3.291515,7657,-4.636281,7302,Total Year-Round Beds,"ES, TH, SH"
452,HI,3599,-13.281467,3121,8.426786,3384,-2.127660,3312,-5.706522,3123,Total Year-Round Beds,"ES, TH, SH"
242,CT,3417,-21.071115,2697,-3.596589,2600,-0.538462,2586,-6.264501,2424,Total Year-Round Beds,"ES, TH, SH"
627,KS,2450,4.530612,2561,1.444748,2598,-13.972286,2235,-6.979866,2079,Total Year-Round Beds,"ES, TH, SH"
1292,NY,88063,1.334272,89238,-0.317129,88955,-5.884998,83720,-7.497611,77443,Total Year-Round Beds,"ES, TH, SH"
1222,NM,1651,49.303452,2465,-3.488844,2379,21.521648,2891,-8.509166,2645,Total Year-Round Beds,"ES, TH, SH"
102,AR,2362,-18.839966,1917,-12.050078,1686,55.100830,2615,-11.357553,2318,Total Year-Round Beds,"ES, TH, SH"
977,MS,1079,1.297498,1093,-11.985361,962,-2.079002,942,-20.700637,747,Total Year-Round Beds,"ES, TH, SH"
417,GU,140,15.000000,161,-9.937888,145,85.517241,269,-44.237918,150,Total Year-Round Beds,"ES, TH, SH"

In [13]:
changes_df.to_csv('HIC_GAvsUSA_changes.csv', index=False)